### ISSUE TITLE
Security - handlerbars

### ISSUE THREAD

**Issue by juanr2001** [dfcook/vue-webpack4-template#15]
Love this template! I found this issue, though!

Replicate steps:
1) `npm audit`

Result:
Run  npm update handlebars --depth 6  to resolve 1 vulnerability

High - Prototype Pollution
-
Package handlebars
-
Dependency of │ jest [dev]
-
Path -  jest > jest-cli > @jest/core > @jest/reporters > istanbul-reports > handlebars
-
More info - https://npmjs.com/advisories/1164

**Comment by dfcook** [comment]
Hi, thanks for the report, I've just patched this.
